const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reducedMotion)document.body.classList.add('motion-ready');
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');entry.target.querySelectorAll('[data-pct]').forEach(bar=>bar.style.width=bar.dataset.pct+'%');observer.unobserve(entry.target)}}),{threshold:.08});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
if(!reducedMotion&&matchMedia('(pointer: fine)').matches)document.querySelectorAll('.tilt').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.transform=`perspective(850px) rotateX(${-(e.clientY-r.top-r.height/2)/r.height*7}deg) rotateY(${(e.clientX-r.left-r.width/2)/r.width*7}deg)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
const progress=document.querySelector('.reading-progress');function updateProgress(){const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h>0?scrollY/h*100:0)+'%'}addEventListener('scroll',updateProgress,{passive:true});addEventListener('resize',updateProgress);updateProgress();
document.getElementById('backToTop').addEventListener('click',()=>scrollTo({top:0,behavior:reducedMotion?'instant':'smooth'}));
const cases={
daira:['Daira — Smart Productivity','Make habits and productivity feel like meaningful progress, using a quest-based mobile companion.','Flutter provides the cross-platform interface, Firebase supports cloud synchronization, and Gemini adds contextual assistance. Offline-first caching keeps the experience useful between connections.',['Quest-based habit workflows and progress analytics','Offline-first data access and real-time synchronization','Contextual Gemini assistance across Android and iOS']],
edu:['EduConnect — University Operations','Students, faculty, and administrators need different views of the same academic workflows.','The local project uses Blazor interactive server rendering on .NET 9. Dedicated student, course, grade, and notification services implement interface-based separation of responsibilities. This version uses in-memory storage.',['Admin student and course management with capacity tracking','Faculty grade submission with automatic CGPA recalculation','Student enrollment, grades, and event-driven notifications','Role-aware navigation and SOLID service design']],
crm:['ClientFlow CRM','Keep customer relationships, leads, scheduling, and billing in one connected workspace.','The local codebase runs on .NET 9 and combines Blazor Server, ASP.NET Core, Entity Framework Core, and SQL Server, with Identity authentication and SignalR notifications.',['Customer, lead, invoice, payment, and task management','Reporting dashboards and interactive charts','Gemini-assisted customer analysis and email drafts','Meeting scheduling with Google Calendar integration']],
blood:['Blood Bank Management System','Organize donor records, blood inventory, and emergency matching workflows in a desktop application.','A Java and SQL Server project focused on practical data relationships behind hospital blood bank operations.',['Donor tracking and inventory management','Blood availability and emergency matching','Persistent records backed by SQL Server']],
evm:['Electronic Voting Machine — 8086','Build a voting workflow with voter ID checks, candidate selection, and results, directly in x86 assembly.','An EMU8086 application built around procedures, macros, keyboard input, and BIOS text output. It stores candidate names, votes, and voter IDs in memory.',['Voter ID checks prevent repeat voting','Password-protected administration and candidate management','Vote totals, winner detection, and text-based result charts']]};
const caseDialog=document.getElementById('caseDialog');document.querySelectorAll('[data-case]').forEach(button=>button.addEventListener('click',()=>{const c=cases[button.dataset.case];document.getElementById('caseTitle').textContent=c[0];document.getElementById('caseBody').innerHTML='<h3>The challenge</h3><p>'+c[1]+'</p><h3>The build</h3><p>'+c[2]+'</p><h3>What to explore</h3><ul>'+c[3].map(x=>'<li>'+x+'</li>').join('')+'</ul>';caseDialog.showModal()}));
document.querySelectorAll('dialog').forEach(dialog=>{dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}})});
const imageDialog=document.getElementById('imageDialog');document.querySelectorAll('.zoomable').forEach(img=>{function openImage(){const full=document.getElementById('fullImage');full.src=img.src;full.alt=img.alt;imageDialog.showModal()}img.addEventListener('click',openImage);img.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openImage()}})});
const lightbox=document.getElementById('lightbox'),video=document.getElementById('lightboxVideo');let videoTrigger;function closeVideo(){video.pause();video.removeAttribute('src');video.load();lightbox.hidden=true;document.body.style.overflow='';videoTrigger?.focus()}
document.querySelectorAll('[data-video]').forEach(button=>button.addEventListener('click',()=>{videoTrigger=button;video.src=button.dataset.video;lightbox.setAttribute('aria-label',button.dataset.title);lightbox.hidden=false;document.body.style.overflow='hidden';document.getElementById('lightboxClose').focus();video.play().catch(()=>{})}));document.getElementById('lightboxClose').addEventListener('click',closeVideo);lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeVideo()});addEventListener('keydown',e=>{if(e.key==='Escape'&&!lightbox.hidden)closeVideo();if(e.key==='Tab'&&!lightbox.hidden){const first=document.getElementById('lightboxClose');if(e.shiftKey&&document.activeElement===first){e.preventDefault();video.focus()}else if(!e.shiftKey&&document.activeElement===video){e.preventDefault();first.focus()}}});
document.getElementById('contactForm').addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('fName').value.trim(),email=document.getElementById('fEmail').value.trim(),message=document.getElementById('fMessage').value.trim();location.href='mailto:rafiullahh2005@gmail.com?subject='+encodeURIComponent('Portfolio enquiry from '+name)+'&body='+encodeURIComponent(`Name: ${name}\nEmail: ${email}\n\n${message}`);document.getElementById('formNote').textContent='Your email app opens a draft. Review it there and send when ready.'});
